// ORIGINAL  → bucket "photos" (private). photos.image_url keeps its location for /api/download.
// PREVIEW   → bucket "previews" (public), watermark in the pixels. photos.watermark_url.
// THUMBNAIL → bucket "previews" (public), watermark in the pixels. photos.thumbnail_url.
export const ORIGINALS_BUCKET = "photos";
export const PREVIEWS_BUCKET = "previews";

// Only images generated by the protected pipeline may be shown publicly. Legacy watermark_url
// values (the original URL plus "?watermark=...") are rejected, so an original is never rendered.
export function protectedImageUrl(value: unknown): string | undefined {
  if (typeof value !== "string" || !value) return undefined;
  return value.includes(`/storage/v1/object/public/${PREVIEWS_BUCKET}/`) ? value : undefined;
}

// Object path inside `bucket` for a Supabase Storage URL (public, signed or authenticated form).
export function storagePathInBucket(url: string, bucket: string): string | null {
  try {
    const match = new URL(url).pathname.match(/\/storage\/v1\/object\/(?:public|sign|authenticated)\/([^/]+)\/(.+)$/);
    return match && match[1] === bucket ? decodeURIComponent(match[2]) : null;
  } catch {
    return null;
  }
}
